name: run-tests
run-name: Run tests
on:
  push:
  pull_request:
    types: [opened, review_requested]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup mill
        uses: zhutmost/setup-mill@main
        with:
          mill-version: 0.11.9
      - name: Compile
        run: mill __.compile
      - name: Test
        run: mill __.test
